import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app"
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
    <ClerkProvider
        appearance={{
            baseTheme: dark
        }}
    >
        <html lang="en">
            <body className={`${inter.className} bg-dark-1`}>{children}</body>
        </html>
    </ClerkProvider>
);

export default RootLayout;
